// All the rooms are here. 
// by T. Fujita
// 
// B: Block(Movable)
// F: Floor
// G: Goal
// P: Player
// W: Wall

var room = [];
    room[0] = [ "WwwwwGwW",
		"WFFFFFFW",
		"WFFFFFFW",
		"WFPFFFFW",
		"WFFFFFFW",
		"WwwwwwwW"]

    room[1] = [ "WwwwwGwW",
		"WFFFFBFW",
		"WFFFFFFW",
		"WFPFFFFW",
		"WFFFFFFW",
		"WwwwwwwW"]

    room[2] = [ "WwwwwwwwwwwwwGwW",
		"WFFFFFFFFFFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFPFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwW"]

    room[3] = [ "WwwwwwwwGwwwwwwW",
		"WFFFFFFFFFFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFFFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFFFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFFFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFFFFFFFW",
		"WFFPFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwW"]

    room[4] = [ "WwwwwwwGwwwwwwwW",
		"WBFBFBFBFBFBFBFW",
		"WFBFBFBFBFBFBFBW",
		"WBFBFBFBFBFBFBFW",
		"WFBFBFBFBFBFBFBW",
		"WBFBFBFBFBFBFBFW",
		"WFBFBFBFBFBFBFBW",
		"WBFBFBFBFBFBFBFW",
		"WFBFBFBFBFBFBFBW",
		"WBFBFBFBFBFBFBFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwW"]

    room[5] = [ "WwwwwwwwwwwwwGwW",
		"WFFBFFFFFFFFFBFW",
		"WFFFBFBFBFBFBFFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFPBFFFFFFBFFFFW",
		"WwwwwwwwwwwwwwwW"]

    room[6] = [ "WwwwwwwwwwwwwGwW",
		"WFFBFBFBFBFBFBFW",
		"WFFFBFBFBFBFBFFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFPBFFFFFFBFFFFW",
		"WwwwwwwwwwwwwwwW"]

    room[7] = [ "WwwwwwwwwwwwwGwW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwW"]

    room[8] = [ "WwwwwwwGwwwwwwwW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwW"]

    room[9] = [ "WwwwwwwGwwwwwwwW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwW"]

    room[10] = ["WwwwwwwGwwwwwwwW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WBWwwBWFFWBWwFBW",
		"WFWFFFWwFWFWFWFW",
		"WFWwFFWwwWFWFWFW",
		"WFWFFFWFwWFWFWFW",
		"WBWwwBWFFWBWwFBW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwW"]

